# Generated by Django 4.0.10 on 2023-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_event_hosted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
